### PR TITLE
add tablet area calc (#58)

### PR DESCRIPTION
**Pull request by kawarbon**
Excuse the formatting done by i-have-no-idea (VSCode or Deno plugin?).

This PR corresponds to issue #58 and to the following places:
https://osu-tableno.deno.dev/
https://github.com/kawarbon/osu-tableno

As discussed, one of the needs was a visualiser:
image

And as discussed after, an explanation or informatics related to the application have been provided access to via a `(i)` icon:
image

As these matters are subject to change, it would be nice to discuss and finalise this further before merging.

### CODE REVIEW

**Comment by Ruben172** [comment]
I'm not gonna lie, I was about to post a comment saying you still didn't add any info, as I didn't notice the small info icon. There's a lot of screen real estate free, so I suggest you use some of that. I also don't see a clear explanation of what this area actually is? Is it just to calculate a 4:3 tablet area based on how much % of your tablet you want to use? Would like to see a further explanation on that as well for this to be useful

**Comment by jamesbt365** [comment]
Also this doesn't account for non 16:9 resolutions?

**Comment by kawarbon** [comment]
> I'm not gonna lie, I was about to post a comment saying you still didn't add any info, as I didn't notice the small info icon. There's a lot of screen real estate free, so I suggest you use some of that. I also don't see a clear explanation of what this area actually is? Is it just to calculate a 4:3 tablet area based on how much % of your tablet you want to use? Would like to see a further explanation on that as well for this to be useful

It essentially does what you just said. It tries to make a near-ideal 4:3 aspect ratio area bounds to match with the playable area of osu! without the unnecessary calls for widened horizontal movement, which seems rather excessive considering a 16:9 osu on native resolution is the equivalent of 16:9 with a 4:3 resolution with black bars. The space by the sides is waste.

I have nothing of amount to add to the 'free real estate'. It'd be easier to suggest me things that the 'free real estate' could be used for, not to tell me to try to use it as I would, if told so, use it for stupid fancy background graphics.

**Comment by kawarbon** [comment]
> Also this doesn't account for non 16:9 resolutions? Also i'm still confused on this is supposed to be used? If you are getting an area for the playfield you're still using the tablet area for outside of the playarea?
> 
> I have no idea how this tool is useful in that regard? It just... warps the tablet area to unnatural ratios? Maybe I'm misunderstanding how this is _supposed_ to be used, but if I am its the fault of the docs, I can see how others will get confused too.

You're getting an area that's about close-enough to match the 'playfield's aspect ratio, which is 4:3, not to map entirely to playfield. It essentially gets you an area that's most suitable for a rather natural movement within the playable field. If you can't hit objects way past the playfield, why account for the unused space? It only creates unnecessarily unnatural horizontal movements (or vertical if you were to play on a vertically positioned monitor......?what)

Look, if you don't need the tool, I'll gladly take it down and keep it to myself as it helped me. Doesn't have to please everybody.

**Pull request closed without merging**
